rds:
  db:
    url: r2dbc-instance.ceox6edjpuog.us-east-2.rds.amazonaws.com/book-rdbc-db
    username: postgres
    password: postgres

spring:
  liquibase:
    url: jdbc:postgresql://${rds.db.url}
    user: ${rds.db.username}
    password: ${rds.db.password}
    change-log: classpath:changelog/changelog-master.xml

  r2dbc:
    url: r2dbc:postgresql://${rds.db.url}
    username:  ${rds.db.username}
    password: ${rds.db.password}
