database:
  url: us-east-2.rds.amazonaws.com/book-rdbc-db
  username: xxxxxxx
  password: xxxxxxxx

spring:
  liquibase:
    url: jdbc:postgresql://${database.url}
    user: ${database.username}
    password: ${database.password}
    change-log: classpath:changelog/changelog-master.xml

  r2dbc:
    url: r2dbc:postgresql://${database.url}
    username:  ${database.username}
    password: ${database.password}
